apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJhdXRocyIgOiB7CiAgICAiZ2hjci5pbyIgOiB7CiAgICAgICJhdXRoIiA6ICJjSFJvY25WemREcG5hSEJmWW10Q1V6VlpWRXhXU1RKVGNHWXhVM1ZWTmtrNVNUazViM1o0VVRGSU1YbHZNVEJ3IgogICAgfQogIH0KfQo=
type: kubernetes.io/dockerconfigjson
