apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGgiIDogewoJCSJnaGNyLmlvIiA6IHsKCQkJImF1dGgiIDogImNIUm9jblZ6ZERwbmFIQmZOM1p4WVdSa2VFWjZUMGhXZEhKTlIwMHpjemhEY205cGNWRXpZek5rTkVZMmJucFAiCgkJfQoJfQp9Cg==
type: kubernetes.io/dockerconfigjson
