apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIiA6IHsKCQkiZ2hjci5pbyIgOiB7CgkJCSJhdXRoIiA6ICJjSFJvY25WemREcG5hSEJmU3pkVWVrMXpiRmhNYlhoa01FUkpTM0JFU2poRFRFRmxiMjlDZFVGaE0yUk9Wbmh4IgoJCX0KCX0KfQo=
type: kubernetes.io/dockerconfigjson
